linters:
    ColorVariable:
        enabled: false
    ColorKeyword:
        enabled: false
    Comment:
        enabled: false
    ElsePlacement:
        style: new_line
    Indentation:
        character: space
        width: 4
    SpaceBeforeBrace:
        allow_single_line_padding: true
    SelectorFormat:
        convention: hyphenated_BEM
